name: api_client
description: "Used for calling API. Contains the Implementation using Dio by default"
version: 0.0.1
# homepage:

environment:
  sdk: ">=3.7.2 <4.0.0"
  flutter: ">=3.0.0 <4.0.0"

resolution: workspace

dependencies:
  # API Calling
  graphql: ^5.2.3

  # For functional programming
  fpdart: ^1.2.0
  dio: ^5.9.0
  dio_cache_interceptor: ^3.5.1
  dio_cache_interceptor_hive_store: ^4.0.0
  path_provider: ^2.1.5
  pretty_dio_logger: ^1.4.0
  hive_ce: ^2.16.0
  hive_ce_flutter: ^2.3.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  hive_ce_generator: ^1.11.0
