name: app_core
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Translation package for localization
  app_translations: ^0.0.1

  # App UI Package
  app_ui: ^0.0.1

  # API Client Package
  api_client: ^0.0.1

  # App Subscription Package
  app_subscription: ^0.0.1

  #App Notification Package
  app_notification_service: ^0.0.1

  # internationalization
  timeago: ^3.7.1

  # environment management
  envied: ^1.3.2

  # secure local storage
  hive_ce: ^2.16.0
  hive_ce_flutter: ^2.3.3

  # Class comparison and form validation
  equatable: ^2.0.8

  # Utils
  logger: ^2.6.2
  path_provider: ^2.1.5

  # State management and dependency injection
  flutter_bloc: ^9.1.1
  bloc_concurrency: ^0.3.0
  get_it: ^9.2.0

  #Routing
  auto_route: ^10.3.0

  # functional programming
  fpdart: ^1.2.0
  data_connection_checker_nulls: ^0.0.2

  # Image picker
  image_picker: ^1.2.1
  permission_handler: ^12.0.1
  device_info_plus: ^11.3.3
  image_cropper: ^11.0.0
  cached_network_image: ^3.4.1
  flutter_svg: ^2.2.3
  top_snackbar_flutter: ^3.3.0
  formz: ^0.8.0

  # For Firebase
  #  firebase_crashlytics: ^4.1.0
  firebase_core: ^3.12.1

  connectivity_plus: ^6.1.3
  firebase_auth: ^5.5.1
  firebase_crashlytics: ^4.3.5

  # Social Sign In
  google_sign_in: ^6.3.0
  sign_in_with_apple: ^7.0.1

  webview_flutter: ^4.10.0
  package_info_plus: ^8.3.0
  firebase_remote_config: ^5.4.3
  # Launch URL
  url_launcher: ^6.3.2


dependency_overrides:
  web: ^1.0.0
  source_gen: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # For generating code
  build_runner: ^2.5.4

  change_app_package_name: ^1.5.0

  # For generating assets code
  flutter_gen: ^5.12.0
  flutter_gen_runner: ^5.12.0

  # For generating routes
  auto_route_generator: ^10.2.3

  # For generating hive model adaptors
  hive_ce_generator: ^1.9.2
  very_good_analysis: ^10.0.0

  # For generating env files
  envied_generator: ^1.1.1

  flutter_launcher_icons: ^0.14.4



flutter_gen:
  output: lib/gen/
  line_length: 80

  integrations:
    flutter_svg: true
    rive: true
    lottie: true

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "../../packages/app_ui/assets/images/logo.png"
