name: app_ui
description: "A new Flutter package project."
version: 0.0.1

environment:
  sdk: ">=3.7.2 <4.0.0"
  flutter: ">=3.0.0 <4.0.0"

resolution: workspace

dependencies:
  animated_custom_dropdown: ^3.1.1
  cached_network_image: ^3.4.1
  equatable: ^2.0.8
  flutter:
    sdk: flutter
  flutter_blurhash: ^0.9.1
  flutter_spinkit: ^5.2.2
  octo_image: ^2.1.0
  skeletonizer: ^2.1.2
  timeago: ^3.7.1
  url_launcher: ^6.3.2
  flutter_svg: ^2.2.3
  pinput: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  very_good_analysis: ^10.0.0
  # For generating code
  build_runner: ^2.10.4

  # For generating assets code
  flutter_gen: ^5.12.0
  flutter_gen_runner: ^5.12.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter_gen:
  assets:
    outputs:
      package_parameter_enabled: true
  output: lib/src/gen/
  line_length: 80

  integrations:
    flutter_svg: true
    rive: true
    lottie: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: opensans
      fonts:
        - asset: assets/fonts/opensans.ttf
